# Generated by Django 5.1.5 on 2025-01-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='user',
            name='ort',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefonnummer'),
        ),
        migrations.AddField(
            model_name='user',
            name='postnummer',
            field=models.CharField(blank=True, max_length=6, verbose_name='Postnummer'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profilbild'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personnummer',
            field=models.CharField(blank=True, max_length=12, verbose_name='Personnummer'),
        ),
    ]
